package lk.ijse.scaleShop.util;

public enum Routes {
    LOGIN,BILL,CUSTOMER,INCOME_REPORT,OWNER_BILL,OWNER_EMPLOYEE,OWNER_INCOME,OWNER_PRODUCT,PRODUCT,SUPPLIER,ADMIN_DASHBOARD,OWNER_DASHBOARD,PLACE_ORDER
}
